"""is_visible

Revision ID: fb48042b62f4
Revises: 69b96091f39a
Create Date: 2024-04-19 20:06:14.223476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb48042b62f4"
down_revision: Union[str, None] = "69b96091f39a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("is_visible", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_visible")
    # ### end Alembic commands ###
